<a href="https://colab.research.google.com/github/2503a52138/DAV-LAB_2/blob/main/2503a52138DAVLAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("/content/earthquake_1995-2023.csv")
print("rows and coloumns:", df.shape)
df.head()     # show the first 5 rows

rows and coloumns: (1000, 19)

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   date_time  1000 non-null   object
 3   cdi        1000 non-null   int64
 4   mmi        1000 non-null   int64
 5   alert      449 non-null    object
 6   tsunami    1000 non-null   int64
 7   sig        1000 non-null   int64
 8   net        1000 non-null   object
 9   nst        1000 non-null   int64
 10  dmin       1000 non-null   float64
 11  gap        1000 non-null   float64
 12  magType    1000 non-null   object
 13  depth      1000 non-null   float64
 14  latitude   1000 non-null   float64
 15  longitude  1000 non-null   float64
 16  location   994 non-null    object
 17  continent  284 non-null    object
 18  country    651 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 148.6+ KB

In [ ]:
display(df.describe(include='all'))

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
count,1000,1000.000000,1000,1000.000000,1000.00000,449,1000.000000,1000.000000,1000,1000.000000,1000.000000,1000.000000,1000,1000.000000,1000.000000,1000.000000,994,284,651
unique,984,NaN,990,NaN,NaN,4,NaN,NaN,11,NaN,NaN,NaN,9,NaN,NaN,NaN,502,6,56
top,"M 6.5 - Kermadec Islands, New Zealand",NaN,11-01-2022 12:39,NaN,NaN,green,NaN,NaN,us,NaN,NaN,NaN,mww,NaN,NaN,NaN,"Kokopo, Papua New Guinea",Asia,Indonesia
freq,3,NaN,3,NaN,NaN,353,NaN,NaN,960,NaN,NaN,NaN,502,NaN,NaN,NaN,29,137,140
mean,NaN,6.940150,NaN,3.605000,6.02700,NaN,0.325000,847.915000,NaN,193.918000,1.125174,20.926290,NaN,74.612541,4.315554,51.486576,NaN,NaN,NaN
std,NaN,0.438148,NaN,3.328972,1.43399,NaN,0.468609,301.802632,NaN,239.045858,2.073164,24.415895,NaN,130.812590,26.633320,117.478302,NaN,NaN,NaN
min,NaN,6.500000,NaN,0.000000,1.00000,NaN,0.000000,650.000000,NaN,0.000000,0.000000,0.000000,NaN,2.700000,-61.848400,-179.968000,NaN,NaN,NaN
25%,NaN,6.600000,NaN,0.000000,5.00000,NaN,0.000000,691.000000,NaN,0.000000,0.000000,0.000000,NaN,16.000000,-13.518500,-71.694450,NaN,NaN,NaN
50%,NaN,6.800000,NaN,4.000000,6.00000,NaN,0.000000,744.000000,NaN,0.000000,0.000000,18.000000,NaN,29.000000,-2.443500,107.791000,NaN,NaN,NaN
75%,NaN,7.100000,NaN,7.000000,7.00000,NaN,1.000000,874.250000,NaN,403.000000,1.549250,27.000000,NaN,55.000000,25.167250,148.364750,NaN,NaN,NaN
max,NaN,9.100000,NaN,9.000000,10.00000,NaN,1.000000,2910.000000,NaN,934.000000,17.654000,239.000000,NaN,670.810000,71.631200,179.662000,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   date_time  1000 non-null   object
 3   cdi        1000 non-null   int64
 4   mmi        1000 non-null   int64
 5   alert      449 non-null    object
 6   tsunami    1000 non-null   int64
 7   sig        1000 non-null   int64
 8   net        1000 non-null   object
 9   nst        1000 non-null   int64
 10  dmin       1000 non-null   float64
 11  gap        1000 non-null   float64
 12  magType    1000 non-null   object
 13  depth      1000 non-null   float64
 14  latitude   1000 non-null   float64
 15  longitude  1000 non-null   float64
 16  location   994 non-null    object
 17  continent  284 non-null    object
 18  country    651 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 148.6+ KB

In [ ]:
display(df.describe(include='all'))

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
count,1000,1000.000000,1000,1000.000000,1000.00000,449,1000.000000,1000.000000,1000,1000.000000,1000.000000,1000.000000,1000,1000.000000,1000.000000,1000.000000,994,284,651
unique,984,NaN,990,NaN,NaN,4,NaN,NaN,11,NaN,NaN,NaN,9,NaN,NaN,NaN,502,6,56
top,"M 6.5 - Kermadec Islands, New Zealand",NaN,11-01-2022 12:39,NaN,NaN,green,NaN,NaN,us,NaN,NaN,NaN,mww,NaN,NaN,NaN,"Kokopo, Papua New Guinea",Asia,Indonesia
freq,3,NaN,3,NaN,NaN,353,NaN,NaN,960,NaN,NaN,NaN,502,NaN,NaN,NaN,29,137,140
mean,NaN,6.940150,NaN,3.605000,6.02700,NaN,0.325000,847.915000,NaN,193.918000,1.125174,20.926290,NaN,74.612541,4.315554,51.486576,NaN,NaN,NaN
std,NaN,0.438148,NaN,3.328972,1.43399,NaN,0.468609,301.802632,NaN,239.045858,2.073164,24.415895,NaN,130.812590,26.633320,117.478302,NaN,NaN,NaN
min,NaN,6.500000,NaN,0.000000,1.00000,NaN,0.000000,650.000000,NaN,0.000000,0.000000,0.000000,NaN,2.700000,-61.848400,-179.968000,NaN,NaN,NaN
25%,NaN,6.600000,NaN,0.000000,5.00000,NaN,0.000000,691.000000,NaN,0.000000,0.000000,0.000000,NaN,16.000000,-13.518500,-71.694450,NaN,NaN,NaN
50%,NaN,6.800000,NaN,4.000000,6.00000,NaN,0.000000,744.000000,NaN,0.000000,0.000000,18.000000,NaN,29.000000,-2.443500,107.791000,NaN,NaN,NaN
75%,NaN,7.100000,NaN,7.000000,7.00000,NaN,1.000000,874.250000,NaN,403.000000,1.549250,27.000000,NaN,55.000000,25.167250,148.364750,NaN,NaN,NaN
max,NaN,9.100000,NaN,9.000000,10.00000,NaN,1.000000,2910.000000,NaN,934.000000,17.654000,239.000000,NaN,670.810000,71.631200,179.662000,NaN,NaN,NaN